version: "3.3"
services:
  test-mycat:
    image: www-web-local
    container_name: test-mycat
    ports:
      - "8066:8066"
    stdin_open: true
    tty: true
    privileged: true
    volumes: #隐射路劲(本地:虚拟机)
      - "/Users/liubo/local/docker/mycat/mount:/www-web/software/mycat"
    networks: #设置ip
      mycat_network:
        ipv4_address: 174.10.0.8
networks:
  mycat_network:
    external:
      name: local-project
